title: =][=
url: "https://beta.bl3ak.com"
baseurl: ""
description: "Dive into grimdark Warhammer projects, miniature painting, conversions, stories, and poetry from a 20 year hobby veteran. Explore the gallery and join the descent into darkness."
plugins:
  - jekyll-paginate-v2
  - jekyll-sass-converter
  - jekyll-feed
  - jekyll-og-image
  - jekyll-seo-tag
  - jekyll-sitemap

pagination:
  enabled: false
  per_page: 6
  permalink: /blog/:num/
  sort_field: date
  sort_reverse: true

gallery_tags:
  - fantasy
  - sci-fi
  - vehicles

jekyll-og-image:
  collections:
    - posts
    - default
    - gallery
  domain: "beta.bl3ak.com"
  canvas:
    width: 1200
    height: 630
  border_bottom:
    width: 20
    fill:
      - "#4285F4"

twitter:
  card: summary_large_image